sensor.camera.rgb:
  black_clip: ActorAttribute(id=black_clip,type=float,value=0)
  blade_count: ActorAttribute(id=blade_count,type=int,value=5)
  bloom_intensity: ActorAttribute(id=bloom_intensity,type=float,value=0.675)
  blur_amount: ActorAttribute(id=blur_amount,type=float,value=1)
  blur_radius: ActorAttribute(id=blur_radius,type=float,value=0)
  calibration_constant: ActorAttribute(id=calibration_constant,type=float,value=16)
  chromatic_aberration_intensity: ActorAttribute(id=chromatic_aberration_intensity,type=float,value=0.5)
  chromatic_aberration_offset: ActorAttribute(id=chromatic_aberration_offset,type=float,value=0)
  enable_postprocess_effects: ActorAttribute(id=enable_postprocess_effects,type=bool,value=True)
  exposure_compensation: ActorAttribute(id=exposure_compensation,type=float,value=0)
  exposure_max_bright: ActorAttribute(id=exposure_max_bright,type=float,value=9)
  exposure_min_bright: ActorAttribute(id=exposure_min_bright,type=float,value=7)
  exposure_mode: ActorAttribute(id=exposure_mode,type=str,value=histogram)
  exposure_speed_down: ActorAttribute(id=exposure_speed_down,type=float,value=1)
  exposure_speed_up: ActorAttribute(id=exposure_speed_up,type=float,value=3)
  focal_distance: ActorAttribute(id=focal_distance,type=float,value=1000)
  fov: ActorAttribute(id=fov,type=float,value=90)
  fstop: ActorAttribute(id=fstop,type=float,value=1.4)
  gamma: ActorAttribute(id=gamma,type=float,value=2.2)
  image_size_x: ActorAttribute(id=image_size_x,type=int,value=960)
  image_size_y: ActorAttribute(id=image_size_y,type=int,value=640)
  iso: ActorAttribute(id=iso,type=float,value=100)
  lens_circle_falloff: ActorAttribute(id=lens_circle_falloff,type=float,value=3)
  lens_circle_multiplier: ActorAttribute(id=lens_circle_multiplier,type=float,value=3)
  lens_flare_intensity: ActorAttribute(id=lens_flare_intensity,type=float,value=0.1)
  lens_k: ActorAttribute(id=lens_k,type=float,value=-1)
  lens_kcube: ActorAttribute(id=lens_kcube,type=float,value=0)
  lens_x_size: ActorAttribute(id=lens_x_size,type=float,value=0.08)
  lens_y_size: ActorAttribute(id=lens_y_size,type=float,value=0.08)
  min_fstop: ActorAttribute(id=min_fstop,type=float,value=1.2)
  motion_blur_intensity: ActorAttribute(id=motion_blur_intensity,type=float,value=0.45)
  motion_blur_max_distortion: ActorAttribute(id=motion_blur_max_distortion,type=float,value=0.35)
  motion_blur_min_object_screen_size: ActorAttribute(id=motion_blur_min_object_screen_size,type=float,value=0.1)
  role_name: ActorAttribute(id=role_name,type=str,value=front)
  sensor_tick: ActorAttribute(id=sensor_tick,type=float,value=0)
  shoulder: ActorAttribute(id=shoulder,type=float,value=0.26)
  shutter_speed: ActorAttribute(id=shutter_speed,type=float,value=200)
  slope: ActorAttribute(id=slope,type=float,value=0.88)
  temp: ActorAttribute(id=temp,type=float,value=6500)
  tint: ActorAttribute(id=tint,type=float,value=0)
  toe: ActorAttribute(id=toe,type=float,value=0.55)
  white_clip: ActorAttribute(id=white_clip,type=float,value=0.04)
sensor.lidar.ray_cast:
  atmosphere_attenuation_rate: ActorAttribute(id=atmosphere_attenuation_rate,type=float,value=0.004)
  channels: ActorAttribute(id=channels,type=int,value=32)
  dropoff_general_rate: ActorAttribute(id=dropoff_general_rate,type=float,value=0.45)
  dropoff_intensity_limit: ActorAttribute(id=dropoff_intensity_limit,type=float,value=0.8)
  dropoff_zero_intensity: ActorAttribute(id=dropoff_zero_intensity,type=float,value=0.4)
  lower_fov: ActorAttribute(id=lower_fov,type=float,value=-30)
  noise_stddev: ActorAttribute(id=noise_stddev,type=float,value=0)
  points_per_second: ActorAttribute(id=points_per_second,type=int,value=56000)
  range: ActorAttribute(id=range,type=float,value=50)
  role_name: ActorAttribute(id=role_name,type=str,value=front)
  rotation_frequency: ActorAttribute(id=rotation_frequency,type=float,value=10)
  sensor_tick: ActorAttribute(id=sensor_tick,type=float,value=0)
  upper_fov: ActorAttribute(id=upper_fov,type=float,value=10)
